# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json
# ==============================================================================
# GLOBAL ENGINE CONFIGURATION
# ==============================================================================
host: "0.0.0.0"
port: 8080
globalTTL: 60
includeAliasesInList: true
healthCheckTimeout: 600

# ==============================================================================
# MACROS & ENVIRONMENT ALIASES
# ==============================================================================
macros:
  llama-server: "llama-server.exe --port ${PORT}"
  default_ctx: 65536
  default_ctk: q8_0
  default_ctv: q8_0
  default_fa: on
  default_args: "--ctx-size ${default_ctx} -ctk ${default_ctk} -ctv ${default_ctv} -fa ${default_fa} -ngl 999"
  dry_args: "--dry-multiplier 0.6 --dry-sequence-breaker '\n' --dry-allowed-length 3 --dry-penalty-last-n 4096"
# ==============================================================================
# INFERENCE ROUTINGS & BACKENDS
# ==============================================================================
models:

# --- GEMMA 4 12B ---
  gemma4-12b:
    name: "Unsloth Gemma 4 12B"
    description: "unsloth/gemma-4-12b-it-qat-GGUF:UD-Q4_K_XL"
    capabilities:
      in:
        - text
        - audio
        - image
      out: ["text"]
      tools: true
      context: 65536
    macros:
      default_ctx: 65536
    cmd: |
      ${llama-server}
      ${default_args}
      -hf unsloth/gemma-4-12b-it-qat-GGUF:UD-Q4_K_XL
      --spec-type draft-mtp
      --spec-draft-n-max 2
      --no-mmproj-offload
      --jinja
    filters:
      setParamsByID:
        "${MODEL_ID}:no_think":
          chat_template_kwargs:
            enable_thinking: false

# --- GEMMA 4 26B MOE ---
  gemma4-26ba4b:
    name: "Unsloth Gemma 4 26B A4B"
    description: "unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL"
    capabilities:
      in: ["text", "image"]
      out: ["text"]
      tools: true
      context: 65536
    macros:
      default_ctx: 65536
    cmd: |
      ${llama-server}
      ${default_args}
      -hf unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
      --spec-type draft-mtp
      --spec-draft-n-max 2
      --no-mmproj-offload
      --jinja
    filters:
      setParamsByID:
        "${MODEL_ID}:no_think":
          chat_template_kwargs:
            enable_thinking: false

# --- GEMMA 4 31B  ---
  gemma4-31b:
    name: "Unsloth Gemma 4 31B"
    description: "unsloth/gemma-4-31B-it-qat-GGUF:UD-Q4_K_XL"
    capabilities:
      in: ["text", "image"]
      out: ["text"]
      tools: true
      context: 65536
    macros:
      default_ctx: 65536
    cmd: |
      ${llama-server}
      ${default_args}
      -hf unsloth/gemma-4-31B-it-qat-GGUF:UD-Q4_K_XL
      --spec-type draft-mtp
      --spec-draft-n-max 2
      --no-mmproj-offload
      --jinja
    filters:
      setParamsByID:
        "${MODEL_ID}:no_think":
          chat_template_kwargs:
            enable_thinking: false

# --- QWEN 3.8 27B ---
  qwen3.8-27b:
    name: "Unsloth Qwen 3.8 27B"
    description: "unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL"
    capabilities:
      in: ["text", "image"]
      out: ["text"]
      tools: true
      context: 65536
    macros:
      default_ctx: 65536
    cmd: |
      ${llama-server}
      ${default_args}
      -hf unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL
      --spec-type draft-mtp
      --spec-draft-n-max 2
      --no-mmproj-offload
      --jinja
    filters:
      setParamsByID:
        "${MODEL_ID}:no_think":
          chat_template_kwargs:
            enable_thinking: false

# --- QWEN 3.6 35B ---
  qwen3.6-35ba3b:
    name: "Unsloth Qwen 3.6 35B A3B"
    description: "unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q3_K_XL"
    capabilities:
      in: ["text", "image"]
      out: ["text"]
      tools: true
      context: 65536
    macros:
      default_ctx: 65536
    cmd: |
      ${llama-server}
      ${default_args}
      -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q3_K_XL
      --spec-type draft-mtp
      --spec-draft-n-max 2
      --no-mmproj-offload
      --jinja
    filters:
      setParamsByID:
        "${MODEL_ID}:no_think":
          chat_template_kwargs:
            enable_thinking: false

# --- UNCENSORED MODELS FOR RESEARCH ---
  gemma4-12b-uncensored:
    name: "HauhauCS/Gemma4-12B-QAT-Uncensored-HauhauCS-Balanced:Q4_K_M"
    description: "HauhauCS/Gemma4-12B-QAT-Uncensored-HauhauCS-Balanced:Q4_K_M"
    capabilities:
      in:
        - text
        - audio
        - image
      out: ["text"]
      tools: true
      context: 65536
    macros:
      default_ctx: 65536
    cmd: |
      ${llama-server}
      ${default_args}
      -hf HauhauCS/Gemma4-12B-QAT-Uncensored-HauhauCS-Balanced:Q4_K_M
      --spec-type draft-mtp
      --spec-draft-n-max 2
      --no-mmproj-offload
      --jinja
    filters:
      setParamsByID:
        "${MODEL_ID}:no_think":
          chat_template_kwargs:
            enable_thinking: false

  qwen3.5-9b-uncensored:
    name: "HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive:Q4_K_M"
    description: "HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive:Q4_K_M"
    capabilities:
      in:
        - text
        - audio
        - image
      out: ["text"]
      tools: true
      context: 65536
    macros:
      default_ctx: 65536
    cmd: |
      ${llama-server}
      ${default_args}
      -hf HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive:Q4_K_M
      --no-mmproj-offload
      --jinja
    filters:
      setParamsByID:
        "${MODEL_ID}:no_think":
          chat_template_kwargs:
            enable_thinking: false